"""CLI-driven code generator for Axiom packages.

Uses the axiom CLI to scaffold all package structure, then uses the LLM to fill
in only proto message fields, function bodies, and test assertions. This
eliminates the entire class of import, axiom.yaml, and signature bugs that arise
when the LLM generates files from scratch.

Workflow:
  1. axiom init <name> --language python --description ... --version ... --no-example-comment
  2. axiom create message <Input> --no-generate / <Output> for each node
  3. LLM fills proto field definitions into messages/messages.proto
  4. axiom generate  (rebuild gen/ from updated proto)
  5. axiom create node <Name> --input X --output Y --type unary --no-generate (all nodes)
  6. axiom generate  (once for all nodes)
  7. LLM fills function body into each nodes/<name>.py
  8. LLM fills test assertions into each nodes/test_<name>.py
  9. git init + push to GitHub (create repo if needed)
  10. axiom publish --json
"""

import json
import os
import re
import shutil
import subprocess
import tempfile

import anthropic
import httpx

from gen.axiom_official_axiom_agent_messages_messages_pb2 import PackageBuildContext, NodeSpec
from gen.axiom_logger import AxiomLogger, AxiomSecrets


def _to_snake(name: str) -> str:
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def _run(cmd: list[str], cwd: str, log: AxiomLogger | None = None, check: bool = True) -> subprocess.CompletedProcess:
    """Run a shell command, logging stdout/stderr."""
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if log:
        if result.stdout.strip():
            log.info(f"[{' '.join(cmd[:2])}] {result.stdout.strip()[:500]}")
        if result.stderr.strip():
            log.info(f"[{' '.join(cmd[:2])} stderr] {result.stderr.strip()[:500]}")
    if check and result.returncode != 0:
        raise RuntimeError(
            f"Command {cmd} failed (exit {result.returncode}):\n"
            f"stdout: {result.stdout[-1000:]}\n"
            f"stderr: {result.stderr[-1000:]}"
        )
    return result


def _write_axiom_credentials(token: str) -> None:
    """Write axiom credentials file so 'axiom publish' can authenticate."""
    path = os.path.expanduser("~/.axiom/credentials")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump({"token": token}, f)


def _ensure_github_repo(org: str, repo: str, token: str, description: str) -> None:
    """Create GitHub repo if it doesn't exist yet."""
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    check = httpx.get(f"https://api.github.com/repos/{org}/{repo}", headers=headers, timeout=30)
    if check.status_code == 404:
        create_resp = httpx.post(
            f"https://api.github.com/orgs/{org}/repos",
            headers=headers,
            json={
                "name": repo,
                "description": description,
                "private": False,
                "auto_init": False,
            },
            timeout=30,
        )
        if create_resp.status_code not in (200, 201):
            raise RuntimeError(f"Failed to create GitHub repo {org}/{repo}: {create_resp.text}")


def _push_to_github(log: AxiomLogger, directory: str, org: str, repo: str, token: str) -> str:
    """Commit all files and force-push to GitHub. Returns the commit SHA."""
    _run(["git", "init"], cwd=directory, log=log)
    _run(["git", "config", "user.email", "agent@axiom.local"], cwd=directory, log=log)
    _run(["git", "config", "user.name", "Axiom Agent"], cwd=directory, log=log)
    _run(["git", "add", "-A"], cwd=directory, log=log)
    _run(["git", "commit", "-m", "feat: generated by axiom agent"], cwd=directory, log=log)

    remote = f"https://x-access-token:{token}@github.com/{org}/{repo}.git"
    _run(["git", "remote", "add", "origin", remote], cwd=directory, log=log)
    _run(["git", "push", "origin", "HEAD:main", "--force"], cwd=directory, log=log)

    sha = _run(["git", "rev-parse", "HEAD"], cwd=directory, log=log)
    return sha.stdout.strip()


def _read_file(path: str) -> str:
    with open(path) as f:
        return f.read()


def _write_file(path: str, content: str) -> None:
    with open(path, "w") as f:
        f.write(content)


def _extract_code_block(text: str) -> str:
    """Extract content from first ```...``` or return text as-is."""
    if "```" in text:
        # Find opening fence (optionally with language tag)
        start = text.index("```")
        after_fence = text[start + 3:]
        # Skip language tag on the same line
        newline = after_fence.find("\n")
        if newline != -1:
            after_fence = after_fence[newline + 1:]
        # Find closing fence
        end = after_fence.find("```")
        if end != -1:
            return after_fence[:end].strip()
    return text.strip()


def _fill_proto_fields(client: anthropic.Anthropic, log: AxiomLogger, tmpdir: str, ctx: PackageBuildContext) -> None:
    """LLM adds field definitions to message stubs in messages/messages.proto."""
    proto_path = os.path.join(tmpdir, "messages", "messages.proto")
    current_proto = _read_file(proto_path)

    node_specs = "\n".join(
        f"- {n.name}: input={n.input_message}, output={n.output_message}, description={n.description}"
        for n in ctx.nodes
    )
    fix_section = (
        f"\n\nFix instructions from previous attempt:\n{ctx.fix_instructions}"
        if ctx.fix_instructions else ""
    )

    prompt = f"""You are editing an Axiom proto file. The messages/messages.proto file below has been
scaffolded with empty message stubs. Your task is to add the appropriate field definitions
to each message based on the node specifications.

Node specifications:
{node_specs}

Package description: {ctx.description}

Current proto file (with empty message stubs):
```proto
{current_proto}
```
{fix_section}

Rules:
- Return ONLY the updated proto file content — no explanation, no markdown, no extra text.
- Keep the syntax = "proto3" header and package declaration exactly as-is.
- Keep all existing message names exactly as-is — do NOT rename or add new messages.
- Add meaningful field definitions to each empty message block.
- Use appropriate proto scalar types (string, int32, int64, float, double, bool, bytes).
- Field numbers must be unique within each message and start at 1.
- Add a short inline comment (// ...) on each field line describing what it holds.
- Do NOT add comments above messages — the HINTS block handles that.
- Do NOT use 'optional' or 'oneof' unless clearly needed."""

    message = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}]
    )

    updated_proto = _extract_code_block(message.content[0].text)
    if not updated_proto.startswith("syntax"):
        # LLM returned extra prose — try harder extraction
        match = re.search(r'syntax\s*=\s*"proto3".*', updated_proto, re.DOTALL)
        if match:
            updated_proto = match.group(0)

    _write_file(proto_path, updated_proto)
    log.info(f"Proto fields filled: {len(updated_proto)} chars")


def _fill_node_body(
    client: anthropic.Anthropic,
    log: AxiomLogger,
    tmpdir: str,
    ctx: PackageBuildContext,
    node: NodeSpec,
    fix_instructions: str,
) -> None:
    """LLM fills the function body in the scaffolded node file."""
    snake_name = _to_snake(node.name)
    impl_path = os.path.join(tmpdir, "nodes", f"{snake_name}.py")

    if not os.path.exists(impl_path):
        log.info(f"Warning: {impl_path} not found, skipping body fill")
        return

    scaffold = _read_file(impl_path)
    proto_path = os.path.join(tmpdir, "messages", "messages.proto")
    proto_content = _read_file(proto_path)

    secrets_info = ""
    if node.required_secrets:
        secrets_list = ", ".join(node.required_secrets)
        secrets_info = (
            f"\nThis node requires secrets: {secrets_list}. "
            f"Access them with: value, found = secrets.get(\"SECRET_NAME\")"
        )

    fix_section = (
        f"\n\nFix instructions from previous attempt:\n{fix_instructions}"
        if fix_instructions else ""
    )

    prompt = f"""You are implementing a single function body in an Axiom Python node file.
The scaffold below has a correct signature, imports, and docstring — your job is to fill
in ONLY the function body, replacing any pass/TODO/placeholder lines.

Proto message definitions (for reference):
```proto
{proto_content}
```

Node description: {node.description}
Input type: {node.input_message}
Output type: {node.output_message}{secrets_info}
{fix_section}

Current scaffolded file:
```python
{scaffold}
```

Rules:
- Return ONLY the complete updated Python file — no explanation, no markdown wrapper.
- Keep the existing imports exactly as-is (do NOT add or remove import lines).
- Keep the function signature exactly as-is.
- Replace the placeholder body with a real implementation that:
  * Reads fields from the input proto message (e.g. input.field_name)
  * Constructs and returns the correct output proto message
  * Uses log.info() for key operations, log.error() for errors
  * Handles exceptions with try/except
- Do NOT import from axiom.context, axiom.logging, or axiom.secrets — use the
  AxiomLogger and AxiomSecrets types already imported in the scaffold."""

    message = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}]
    )

    updated_code = _extract_code_block(message.content[0].text)
    _write_file(impl_path, updated_code)
    log.info(f"Node body filled: nodes/{snake_name}.py ({len(updated_code)} chars)")


def _fill_test_assertions(
    client: anthropic.Anthropic,
    log: AxiomLogger,
    tmpdir: str,
    ctx: PackageBuildContext,
    node: NodeSpec,
) -> None:
    """LLM fills meaningful test assertions into the scaffolded test file."""
    snake_name = _to_snake(node.name)
    # axiom create node generates <name>_test.py (e.g. add_test.py)
    test_path = os.path.join(tmpdir, "nodes", f"{snake_name}_test.py")

    if not os.path.exists(test_path):
        log.info(f"Warning: {test_path} not found, skipping test fill")
        return

    scaffold = _read_file(test_path)
    impl_path = os.path.join(tmpdir, "nodes", f"{snake_name}.py")
    impl_code = _read_file(impl_path) if os.path.exists(impl_path) else ""

    proto_path = os.path.join(tmpdir, "messages", "messages.proto")
    proto_content = _read_file(proto_path)

    prompt = f"""You are filling in test assertions for an Axiom node test file.
The scaffold below has the correct imports and test structure — fill in meaningful
assert statements.

Node implementation (for reference):
```python
{impl_code}
```

Proto definitions (for reference):
```proto
{proto_content}
```

Current test scaffold:
```python
{scaffold}
```

Rules:
- Return ONLY the complete updated test file — no explanation, no markdown wrapper.
- Keep all existing imports exactly as-is.
- Keep the function signatures (def test_...) exactly as-is.
- Replace pass/TODO/placeholder lines with real assertions using:
  * Concrete proto message construction: input_msg = {node.input_message}(field=value)
  * isinstance checks: assert isinstance(result, {node.output_message})
  * Field value assertions: assert result.some_field == expected_value
- Each test function must have at least one assert statement.
- Mock the log and secrets parameters: log = Mock(), secrets = Mock()
- Do NOT test for error conditions unless clearly appropriate.
- Keep test functions simple and focused on happy-path scenarios."""

    message = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}]
    )

    updated_tests = _extract_code_block(message.content[0].text)
    _write_file(test_path, updated_tests)
    log.info(f"Test assertions filled: nodes/test_{snake_name}.py ({len(updated_tests)} chars)")


def code_generator(log: AxiomLogger, secrets: AxiomSecrets, input: PackageBuildContext) -> PackageBuildContext:
    """CLI-driven package code generation.

    Scaffolds the package using the axiom CLI, then uses the LLM to fill in only
    the proto fields, function bodies, and test assertions. After a successful
    build + test (inside Docker via axiom publish), clears fix_instructions.
    On error, populates publish_error for PackageErrorAnalyser to diagnose.
    """
    api_key, _ = secrets.get("ANTHROPIC_API_KEY")
    axiom_api_key, _ = secrets.get("AXIOM_API_KEY")
    github_token, _ = secrets.get("GITHUB_TOKEN")

    client = anthropic.Anthropic(api_key=api_key)

    fix_instructions = input.fix_instructions or ""
    pkg_short = input.name.split("/")[-1] if "/" in input.name else input.name
    org = "AxiomIDE"
    registry_url = os.environ.get("REGISTRY_URL", "http://axiom-registry.default.svc.cluster.local:8082")

    tmpdir = tempfile.mkdtemp()
    try:
        log.info(f"Starting CLI-driven code generation for {input.name} (iteration {input.iteration})")

        # 1. axiom init — writes axiom.yaml + scaffold into cwd (tmpdir)
        log.info(f"Running: axiom init {input.name} --language python --no-example-comment")
        _run([
            "axiom", "init", input.name,
            "--language", "python",
            "--description", input.description or input.name,
            "--version", input.version or "0.1.0",
            "--no-example-comment",
        ], cwd=tmpdir, log=log)

        # axiom init uses os.Getwd() so all files land directly in tmpdir
        pkg_dir = tmpdir

        # 2. Create message stubs for all unique input/output types.
        # Use --no-generate to skip the auto-generate step after each message;
        # we will run axiom generate once after the LLM fills all proto fields.
        created_messages: set[str] = set()
        for node in input.nodes:
            for msg_name in [node.input_message, node.output_message]:
                if msg_name and msg_name not in created_messages:
                    log.info(f"Creating message stub: {msg_name}")
                    result = _run(
                        ["axiom", "create", "message", msg_name, "--no-generate"],
                        cwd=pkg_dir, log=log, check=False
                    )
                    if result.returncode == 0:
                        created_messages.add(msg_name)
                    else:
                        # Message may already exist (e.g. shared output type)
                        log.info(f"Message {msg_name} may already exist, continuing")
                        created_messages.add(msg_name)

        # 3. LLM fills in proto field definitions
        log.info("Asking LLM to fill proto message fields...")
        _fill_proto_fields(client, log, pkg_dir, input)

        # 4. axiom generate (rebuild gen/ from updated proto)
        log.info("Running: axiom generate")
        _run(["axiom", "generate"], cwd=pkg_dir, log=log)

        # Write requirements.txt so axiom validate passes the language-files check.
        req_content = input.requirements_txt or "grpcio>=1.60.0\ngrpcio-tools>=1.60.0\nprotobuf>=4.25.0\n"
        _write_file(os.path.join(pkg_dir, "requirements.txt"), req_content)
        log.info("Wrote requirements.txt")

        # 5. Create node scaffolds for each node.
        # Use --no-generate on every node to avoid running generate N times;
        # we run axiom generate once after all nodes are scaffolded.
        for node in input.nodes:
            log.info(f"Creating node scaffold: {node.name}")
            cmd = [
                "axiom", "create", "node", node.name,
                "--input", node.input_message,
                "--output", node.output_message,
                "--type", node.node_type or "unary",
                "--no-generate",
            ]
            if node.description:
                cmd += ["--description", node.description]
            _run(cmd, cwd=pkg_dir, log=log)

        # Run axiom generate once after all nodes are scaffolded to produce
        # the service stubs needed by the node implementations.
        log.info("Running: axiom generate (after node scaffolding)")
        _run(["axiom", "generate"], cwd=pkg_dir, log=log)

        # 6. LLM fills in function bodies and test assertions for each node
        for node in input.nodes:
            log.info(f"Filling function body for node: {node.name}")
            _fill_node_body(client, log, pkg_dir, input, node, fix_instructions)

            log.info(f"Filling test assertions for node: {node.name}")
            _fill_test_assertions(client, log, pkg_dir, input, node)

        # 7. Ensure GitHub repo exists and push code
        log.info(f"Ensuring GitHub repo {org}/{pkg_short} exists...")
        _ensure_github_repo(org, pkg_short, github_token, input.description or input.name)

        log.info("Pushing code to GitHub...")
        commit_sha = _push_to_github(log, pkg_dir, org, pkg_short, github_token)
        input.repo_url = f"https://github.com/{org}/{pkg_short}"
        input.commit_hash = commit_sha
        log.info(f"Pushed to {input.repo_url}@{commit_sha[:8]}")

        # 8. Write axiom credentials and run axiom publish --json
        _write_axiom_credentials(axiom_api_key)

        env = os.environ.copy()
        env["AXIOM_API_URL"] = registry_url

        log.info("Running: axiom publish --json")
        result = subprocess.run(
            ["axiom", "publish", "--json"],
            cwd=pkg_dir, capture_output=True, text=True, env=env
        )

        log.info(f"axiom publish stdout: {result.stdout[-1000:]}")
        if result.stderr.strip():
            log.info(f"axiom publish stderr: {result.stderr[-500:]}")

        if result.returncode != 0:
            # Try to parse structured JSON error first
            try:
                data = json.loads(result.stdout) if result.stdout.strip() else {}
                base_error = data.get("error") or result.stderr[-500:] or result.stdout[-500:]
                # Include failing check details so PackageErrorAnalyser has actionable info
                failed_checks = [
                    c for c in data.get("checks", [])
                    if not c.get("ok") and not c.get("warning")
                ]
                if failed_checks:
                    details = "; ".join(
                        f"{c['category']}: {c['name']}" + (f" — {c['detail']}" if c.get('detail') else "")
                        for c in failed_checks
                    )
                    input.publish_error = f"{base_error}. Failing checks: {details}"
                elif data.get("build_log"):
                    input.publish_error = f"{base_error}.\n\nBuild output (last lines):\n{data['build_log']}"
                else:
                    input.publish_error = base_error
            except (json.JSONDecodeError, ValueError):
                input.publish_error = (result.stderr or result.stdout)[-500:]
            input.publish_success = False
            log.info(f"Publish failed: {input.publish_error}")
        else:
            try:
                data = json.loads(result.stdout)
                input.publish_success = data.get("success", False)
                node_ids = [n.get("id", "") for n in data.get("nodes", []) if n.get("id")]
                if node_ids:
                    for nid in node_ids:
                        input.node_ids.append(nid)
                if not input.publish_success:
                    input.publish_error = data.get("error", "unknown error")
                    log.info(f"Publish reported failure: {input.publish_error}")
                else:
                    input.publish_error = ""
                    log.info("Package published successfully")
            except (json.JSONDecodeError, ValueError):
                # Fallback: if JSON parse fails but exit code was 0, treat as success
                input.publish_success = True
                input.publish_error = ""
                log.info("Package published successfully (non-JSON output)")

        # Clear fix_instructions after consuming them
        input.fix_instructions = ""

        return input

    except Exception as e:
        log.error(f"CodeGenerator failed: {e}")
        import traceback
        log.error(traceback.format_exc())
        input.has_error = True
        input.publish_success = False
        input.publish_error = str(e)
        input.error_summary = f"CodeGenerator error (iteration {input.iteration}): {e}"
        input.fix_instructions = f"The code generation failed with: {e}\nReview the error and try a different approach."
        return input

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
