import os
import re
import subprocess
import tempfile
import shutil

import httpx

from gen.axiom_official_axiom_agent_messages_messages_pb2 import PackageBuildContext
from gen.axiom_logger import AxiomLogger, AxiomSecrets


def _to_snake(name: str) -> str:
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def publisher(log: AxiomLogger, secrets: AxiomSecrets, input: PackageBuildContext) -> PackageBuildContext:
    github_token, _ = secrets.get("GITHUB_TOKEN")
    axiom_api_key, _ = secrets.get("AXIOM_API_KEY")
    tmpdir = tempfile.mkdtemp()
    try:
        pkg_short = input.name.split("/")[-1] if "/" in input.name else input.name
        org = "AxiomIDE"
        repo_url = f"https://github.com/{org}/{pkg_short}"

        headers = {
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github.v3+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        check = httpx.get(f"https://api.github.com/repos/{org}/{pkg_short}", headers=headers)
        if check.status_code == 404:
            create_resp = httpx.post(
                f"https://api.github.com/orgs/{org}/repos",
                headers=headers,
                json={
                    "name": pkg_short,
                    "description": input.name,
                    "private": False,
                    "auto_init": False,
                }
            )
            if create_resp.status_code not in (200, 201):
                input.publish_success = False
                input.publish_error = f"Failed to create GitHub repo: {create_resp.text}"
                return input

        os.makedirs(os.path.join(tmpdir, "messages"), exist_ok=True)
        os.makedirs(os.path.join(tmpdir, "nodes"), exist_ok=True)

        if input.axiom_yaml:
            with open(os.path.join(tmpdir, "axiom.yaml"), "w") as f:
                f.write(input.axiom_yaml)

        if input.proto_content:
            with open(os.path.join(tmpdir, "messages", "messages.proto"), "w") as f:
                f.write(input.proto_content)

        reqs = input.requirements_txt or "grpcio>=1.60.0\ngrpcio-tools>=1.60.0\nprotobuf>=4.25.0\n"
        with open(os.path.join(tmpdir, "requirements.txt"), "w") as f:
            f.write(reqs)

        for node in input.nodes:
            snake_name = _to_snake(node.name)
            if node.source_code:
                with open(os.path.join(tmpdir, "nodes", f"{snake_name}.py"), "w") as f:
                    f.write(node.source_code)
            if node.test_code:
                with open(os.path.join(tmpdir, "nodes", f"test_{snake_name}.py"), "w") as f:
                    f.write(node.test_code)

        with open(os.path.join(tmpdir, ".gitignore"), "w") as f:
            f.write("# Axiom build artifacts\n.axiom/\ngen/\n__pycache__/\n*.pyc\n.venv/\n")

        commit_sha = _push_to_github(log, tmpdir, org, pkg_short, github_token)

        if not commit_sha:
            input.publish_success = False
            input.publish_error = "Failed to push files to GitHub"
            input.repo_url = repo_url
            return input

        input.repo_url = repo_url
        input.commit_hash = commit_sha
        return _axiom_publish(log, input, axiom_api_key)

    except Exception as e:
        log.error(f"Publisher failed: {e}")
        input.publish_success = False
        input.publish_error = str(e)
        return input
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


def _push_to_github(log: AxiomLogger, directory: str, org: str, repo: str, token: str) -> str:
    subprocess.run(["git", "init"], cwd=directory, capture_output=True)
    subprocess.run(["git", "config", "user.email", "agent@axiom.local"], cwd=directory, capture_output=True)
    subprocess.run(["git", "config", "user.name", "Axiom Agent"], cwd=directory, capture_output=True)
    subprocess.run(["git", "add", "-A"], cwd=directory, capture_output=True)
    subprocess.run(["git", "commit", "-m", "feat: generated by axiom agent"], cwd=directory, capture_output=True)

    remote = f"https://x-access-token:{token}@github.com/{org}/{repo}.git"
    result = subprocess.run(
        ["git", "push", remote, "HEAD:main", "--force"],
        cwd=directory, capture_output=True, text=True
    )

    if result.returncode != 0:
        log.error(f"git push failed: {result.stderr}")
        return ""

    sha_result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=directory, capture_output=True, text=True
    )
    return sha_result.stdout.strip()


def _axiom_publish(log: AxiomLogger, ctx: PackageBuildContext, api_key: str) -> PackageBuildContext:
    registry_url = os.environ.get("REGISTRY_URL", "http://axiom-registry:8082")

    try:
        resp = httpx.post(
            f"{registry_url}/packages/publish",
            headers={"Authorization": f"Bearer {api_key}"},
            json={
                "repo_url": ctx.repo_url,
                "commit_hash": ctx.commit_hash,
            },
            timeout=300.0,
        )

        if resp.status_code == 200:
            data = resp.json()
            ctx.publish_success = True
            ctx.node_ids.extend(data.get("node_ids", []))
        else:
            ctx.publish_success = False
            ctx.publish_error = f"Registry returned {resp.status_code}: {resp.text[:500]}"
    except Exception as e:
        ctx.publish_success = False
        ctx.publish_error = str(e)

    return ctx
